### ISSUE TITLE
How about GPU?

### ISSUE THREAD

**Issue by Airotong** [chenxinpeng/S2VT#7]
I could run these code in my cpu tensorflow, but the training time is quite long. So I downloaded GPU tensorflow and wanted to run model_RGB.py again, but there were many peoblems. The most biggest problem is ResourceExhaustedError:OMM when allocating tensor with shape[3000,4000]. 
I want to know if these codes just for CPU? And we cannot simply apply them to GPU environment?
Thank you for your reply! I am new to video description.

**Comment by Airotong** [comment]
I used "with tf.device("/cpu:0")" in my GPU envrionment, but it still did not work.
Please help me ! T T

**Comment by siyilingting** [comment]
Hi, @Airotong , I have encountered a similar situation. Is this problem solved?

**Comment by knwng** [comment]
ResourceExhaustedError means you don't have enough GPU memory, you can try to use smaller data shape or upgrade your GPU

**Comment by Airotong** [comment]
How could I set the data size? I used smaller batch_size, but it lead to the same problem.

**Comment by siyilingting** [comment]
@Airotong You can try this. ` train_op = tf.train.AdamOptimizer(learning_rate).minimize(tf_loss,aggregation_method=tf.AggregationMethod.EXPERIMENTAL_ACCUMULATE_N)`
or
`train_op = tf.train.AdamOptimizer(learning_rate).minimize(tf_loss, aggregation_method=tf.AggregationMethod.EXPERIMENTAL_TREE)`
Maybe can solve your problem.

**Comment by Airotong** [comment]
Thank you for your reply!
But I still met the same problem though I used`train_op = tf.train.AdamOptimizer(learning_rate).minimize(tf_loss,aggregation_method=tf.AggregationMethod.EXPERIMENTAL_ACCUMULATE_N)` or `train_op = tf.train.AdamOptimizer(learning_rate).minimize(tf_loss, aggregation_method=tf.AggregationMethod.EXPERIMENTAL_TREE)`
